version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8001:8000"
    volumes:
      - ./api:/app
      - ./frontend/jekyll_site/_site:/app/static
    env_file:
      - .env
    environment:
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
      - STRAVA_REFRESH_TOKEN=${STRAVA_REFRESH_TOKEN}
      - JEKYLL_SITE_PATH=/app/static
    command: >
      sh -c "while [ ! -d /app/static ]; do sleep 1; done &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - jekyll

  jekyll:
    image: jekyll/jekyll:4.2.2
    ports:
      - "4000:4000"
    volumes:
      - ./frontend/jekyll_site:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
      - BUNDLE_GEMFILE=/srv/jekyll/Gemfile
    command: >
      sh -c "gem install bundler:2.6.7 &&
             bundle install &&
             bundle exec jekyll build &&
             bundle exec jekyll serve --watch --force_polling"
