[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "python311Packages.virtualenv",
    "ruby",
    "rubyPackages.bundler_2",
    "rubyPackages.jekyll"
]

[phases.install]
cmds = [
    # Set up Python environment
    "python -m venv venv",
    ". venv/bin/activate",
    "pip install -r api/requirements.txt",
    
    # Set up Ruby environment
    "gem install bundler",
    "cd frontend/jekyll_site",
    "bundle install",
    "bundle exec jekyll build",
    "cd ../.."
]

[start]
cmd = "cd api && uvicorn app.main:app --host 0.0.0.0 --port $PORT" 